### PR TITLE
Use zed-js for all Zed queries

### LINKED ISSUE #4: Use zed-js client
In its first version, the plugin accesses the Zed API directly over HTTP and receives a query result as JSON. This requires it to issue some bonus mini queries to do things like check the shape count or grab the field names & types for assembling the data frame. However, the zed-js client that @jameskerr is working on would allow it to issue a single query and get back all that meta-info as a side effect, which would allow the removal of a significant amount of code. @jameskerr also suggested we might move the plugin into the planned Zealot "monorepo" so it can live alongside its zed-js dependency. I can look at doing both of these things at the same time when Zealot is ready.

### LINKED ISSUE #10: Handle string-typed Time Fields
A community zync user attempted to use the plugin and happened to have a `string`-typed field that held a timestamp value and was stumped when the plugin wasn't able to plot data just by specifying it as the Time Field. While won't be as efficient to do the conversions on the fly at the JavaScript layer, it would surely be user friendly if the plugin could somehow handle this case automatically (and perhaps issue a warning to the user so they know they're not seeing ideal performance.)

For now, a change in #14 has made it such that the plugin does detect when the user has picked a non-`time` field and surfaces an error message advising them as to why it's not working.

### PR DESCRIPTION
**Pull request by philrz**
Closes #4

### CODE REVIEW

File: src/datasource.ts [hunk 1]
```diff
@@ -68,113 +59,140 @@ export class DataSource extends DataSourceApi<MyQuery, MyDataSourceOptions> {
...
+    //    shape their data and try again.
+    //
+    // In order to tell the difference between these two cases we need to execute
+    // the following special query focused on just the Time Field.
+    } else if (shapes.length === 0) {
+      const timeCheckQuery = 'from "' +
+        pool +
+        '" | union(typeof(' +
+        timeField +
+        '))';
```
Comment (nwt) [inline src/datasource.ts]: I think a template literal would make this a little more readable.
```suggestion
      const timeCheckQuery = `from "${pool}" | union(typeof(${timeField}))`;
```

**Review by jameskerr — APPROVED** [review]
Looks good to go to me. Next time I'm working on the zed-js Client, I'll refer back to it's usage in this plugin to see if I can improve things.
